name: 빌드 및 배포 

on:
  push:
    branches: [ main ]

env:
  USERNAME: masungil

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 원격저장소에서 소스를 복사
        uses: actions/checkout@v3

      - name: 소스파일을 docker이미지로 빌드한다
        run: |
          cd backend
          docker build -t ${{env.USERNAME}}/backend:latest .
      
      - name: docker hub에 로그인을 한다
        run: docker login -u ${{env.USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: 생성된 이미지를 docker hub에 push 한다
        run: docker push ${{env.USERNAME}}/backend:latest

  deploy:
    needs: build-docker-image
    name: deploy
    runs-on: [ self-hosted, label-kosa2]
    steps:
      - name: docker hub에 로그인을 한다
        run: docker login -u ${{env.USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: 서비스 실행
        run: |
          cd /home/ubuntu/step3
          docker compose up -d 